services:
  nio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nio-server
    network_mode: "host"
    ports:
      - "${PORT:-3002}:${PORT:-3002}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - BUN_CONFIG_NO_IPV6=1

    dns:
      - 1.1.1.1
      - 8.8.8.8

    restart: unless-stopped

